In [1]:
###Given Data
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

1) 
Yes, there can be a difference in the data type of variables list_ and array_list. Variable list_ is likely a regular Python list, while array_list might be a NumPy array or a Python list created using the array module. To determine the data types of both variables, you can use the type() function in Python.

In [3]:
# Assuming list_ and array_list are already defined
# Printing the data types of both variables
print("Data type of list_: ", type(list_))
print("Data type of array_list: ", type(array_list))

Data type of list_:  <class 'list'>
Data type of array_list:  <class 'numpy.ndarray'>


2) 

In [4]:
# Assuming list_ and array_list are already defined

# Printing the data type of each element in list_
print("Data types of elements in list_:")
for elem in list_:
    print(type(elem))

# Printing the data type of each element in array_list
print("\nData types of elements in array_list:")
for elem in array_list:
    print(type(elem))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


3) 

In [5]:
###Given Changes
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in the data type of the elements present in list_ and array_list after the conversion. In the provided code, array_list is created by converting the Python list list_ to a NumPy array with the specified data type int. Therefore, all elements in array_list will have the data type int, whereas the elements in list_ may have various data types depending on the original list contents.
</br>
To print the data types of each element in both variables list_ and array_list, you can use the same approach as before, but considering that all elements in array_list will have the same data type int

In [6]:
###Given Data
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

4) 

In [7]:
import numpy as np

# Assuming num_array is already defined
# Example num_array
num_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# (i) Finding the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# (ii) Finding the size of num_array
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (3, 3)
Size of num_array: 9


5) 

In [8]:
import numpy as np

# Create a NumPy array of zeros with shape (3, 3)
zero_array = np.zeros((3, 3))

# Print the zero array
print("NumPy array of zeros:")
print(zero_array)

NumPy array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6) 

In [9]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

# Print the identity matrix
print("Identity matrix of shape (5, 5):")
print(identity_matrix)

Identity matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
